name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Resolve Dependencies
      run: swift package resolve
    
    - name: Build for Testing
      run: swift build --build-tests
    
    - name: Run Tests
      run: swift test --parallel --xunit-output=test-results.xml
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xml
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: 'test-results.xml'
        check_name: 'Test Results'
        fail_on_failure: true

  code-coverage:
    name: Code Coverage
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Generate Coverage Report
      run: swift test --enable-code-coverage
    
    - name: Convert Coverage to LCOV
      run: |
        xcrun llvm-cov export \
          .build/debug/RecapPackageTests.xctest/Contents/MacOS/RecapPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          -format=lcov \
          -ignore-filename-regex=".build|Tests" \
          > coverage.lcov
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.lcov
        flags: unittests
        name: recap-coverage
        fail_ci_if_error: false