name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-deriveddata-${{ hashFiles('Recap/Recap.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-deriveddata-
    
    - name: Build and Test
      run: |
        cd Recap
        xcodebuild test \
          -project Recap.xcodeproj \
          -scheme Recap \
          -destination 'platform=macOS' \
          -resultBundlePath TestResults \
          -enableCodeCoverage YES \
          | xcbeautify
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: Recap/TestResults.xcresult
    
    - name: Generate Coverage Report
      run: |
        cd Recap
        xcrun xccov view --report --json TestResults.xcresult > coverage.json
    
    - name: Upload Coverage
      uses: codecov/codecov-action@v5
      with:
        file: Recap/coverage.json
        flags: unittests
        name: recap-coverage
        fail_ci_if_error: false